# This is a conda environment. For more information on how to install:
# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

name: workflows
channels:
    - conda-forge
    - bioconda
    - default
dependencies:
    - pytest-workflow
    - miniwdl