name: Python CI

on: [push]

jobs:
    python-black:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Python Black
          uses: cytopia/docker-black@0.11
          with:
            path: 'docker_scripts/'
    python-lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v5
          with:
            cache: 'pip'
            python-version: '3.11.3'
        - run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
        - name: Pyright
          uses: jakebailey/pyright-action@v2
          with:
            working-directory: 'docker_scripts/'